FROM openjdk:15
VOLUME /tmp
ADD config/ /deploy/

COPY ./springboot-graphql-api/target/springboot-graphql-api-deployed.jar /deploy/
ADD ./config/application.yml .

EXPOSE 8080

ENTRYPOINT ["java", "-Dspring.profiles.active=local","-Djava.security.egd=file:/dev/./urandom --spring.config.location=classpath:file:/config/application.yml","-jar","/deploy/springboot-graphql-api-deployed.jar"]